### ISSUE TITLE
Osram Lightify Classic B40 TW registered as unknown zigbee device

### ISSUE THREAD

**Issue by bsnellen** [athombv/com.osram.lightify.zigbee#7] opened 2017-08-21 18:36 UTC
When connecting a new Osram Ligthify Classic B40 TW bulb (the E14 tunable white bulb) it is registered as a unknown zigbee device. 
It can be turned on and off,  but the white tone can not be adjusted.

**Comment by CyberSponk** [comment] 2017-08-21 19:50
Not implemented at the moment. Take a look here: https://github.com/athombv/com.osram.lightify.zigbee/issues/4
The Bulb is called: B40 TW 6W E14

**Comment by RobinBol** [comment] 2017-09-25 15:50
Duplicate of https://github.com/athombv/com.osram.lightify.zigbee/issues/4

**Closed by RobinBol** 2017-09-25 15:50 UTC
