### ISSUE TITLE
Control/SetUp Bulbs with Flows 

### ISSUE THREAD

**Issue by CyberSponk** [athombv/com.osram.lightify.zigbee#10] opened 2017-10-02 18:42 UTC
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Control/SetUp/Update (e.g. On/Off, Brightness, Color) Bulbs with Flows. Tested with 6 Bulbs in the Then-Column and tryed to set e.g. Brightness.

**What was the result?**
After running the Flow max. 4 Bulbs updated with the given settings. Flow needs to run up to 5 times before all Bulbs updated with given settings.

**What did you expect as result?**
One Flow, one execution > All Bulbs updated with the given settings.

**Any other remarks**
Tested with Osram Lightify GU10White, GU10Color and E27Color. Including to Homey without no Problems. Running Homey at the moment with 18 Lightify-Bulbs. Made also a Git here: https://github.com/athombv/homey/issues/1859. I could not find out if this Issue is a Homey-ZiggBee-Problem or a App-Problem.

**Please attach a Homey System log (Settings -> System -> Send Log)**
If needed let me know.

**Comment by RobinBol** [comment] 2017-10-05 15:48
Closing as duplicate of https://github.com/athombv/homey/issues/1859

**Closed by RobinBol** 2017-10-05 15:48 UTC
